### ISSUE TITLE
Name Regex Fails for Hyphenated names

### ISSUE THREAD

**Issue by usmansbk** [anubabajide/HNG-Task-2-Team-Falcon#1050]
Ademola-Alege
Ummul-Khair

I'll start fixing it now

**Comment by temmyjay001** [comment]
Okay

**Comment by AndikanAffiah** [comment]
a possible fix would look like..


`[A-Z][a-z]{1,}-{0,1}\s[A-Z][a-z]+`

**Comment by usmansbk** [comment]
@AndikanAffiah can you try testing it with different outputs. We're currently adding a new required feature

**Comment by dfnsdavid** [comment]
Hi @usmansbk this is not fixed yet.
A Python script failed because of it

**Comment by usmansbk** [comment]
Fixed
